groups:
  - name: kopia_alerts
    rules:
      # Backup Status Alerts
      - alert: KopiaBackupFailed
        expr: kopia_backup_status == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Backup failed for {{ $labels.source }}"
          description: "Backup operation has failed on {{ $labels.instance }} for source {{ $labels.source }}"

      - alert: KopiaBackupTooOld
        expr: time() - kopia_last_backup_timestamp > 86400
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Backup too old for {{ $labels.source }}"
          description: "Last successful backup is older than 24 hours for source {{ $labels.source }}"

      # Repository Alerts
      - alert: KopiaRepositoryDisconnected
        expr: kopia_repository_status == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Repository disconnected"
          description: "Kopia repository is disconnected on {{ $labels.instance }}"

      - alert: KopiaRepositoryLowSpace
        expr: kopia_repository_free_space_bytes / 1024/1024/1024 < 10
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low repository space"
          description: "Less than 10GB free space in repository on {{ $labels.instance }}"

      # Cache Alerts
      - alert: KopiaCacheHighMissRate
        expr: rate(kopia_cache_misses_total[5m]) / (rate(kopia_cache_hits_total[5m]) + rate(kopia_cache_misses_total[5m])) > 0.5
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High cache miss rate"
          description: "Cache miss rate is above 50% on {{ $labels.instance }}"

      # Performance Alerts
      - alert: KopiaBackupDurationHigh
        expr: kopia_backup_duration_seconds > 7200
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Long backup duration"
          description: "Backup taking more than 2 hours for source {{ $labels.source }}"

      # System Alerts
      - alert: KopiaExporterDown
        expr: up{job="kopia"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Kopia exporter down"
          description: "Kopia exporter is not responding on {{ $labels.instance }}"