apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: ${ZABBIX_URL}
    jsonData:
      username: ${ZABBIX_USERNAME}
      trendsFrom: "7d"
      trendsRange: "4d"
      cacheTTL: "1h"
      timeout: 30
    secureJsonData:
      password: ${ZABBIX_PASSWORD} 