version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "${LOG_MAX_SIZE:-100M}"
    max-file: "${LOG_MAX_FILES:-7}"

services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: kopia-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-15d}'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ${PROMETHEUS_CONFIG_DIR:-./prometheus/config}:/etc/prometheus
      - ${PROMETHEUS_DATA_DIR:-/var/lib/prometheus}:/prometheus
    ports:
      - "${PROMETHEUS_UI_PORT:-9090}:9090"
    networks:
      - monitoring_network
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"
    profiles:
      - base-metrics
      - grafana-local
      - zabbix-local
      - zabbix-external
      - full-stack
    logging: *default-logging

  kopia-exporter:
    build: 
      context: ${PWD}/monitoring/exporters/kopia-exporter
      dockerfile: Dockerfile
    container_name: kopia-exporter
    volumes:
      - ${KOPIA_BASE_DIR:-/var/lib/kopia}:/app/data:ro
    ports:
      - "${KOPIA_EXPORTER_PORT:-9091}:9091"
    networks:
      - monitoring_network
      - kopia_network
    restart: unless-stopped
    profiles:
      - base-metrics
      - grafana-local
      - grafana-external
      - zabbix-local
      - zabbix-external
      - grafana-zabbix-external
      - full-stack
    logging: *default-logging

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION:-latest}
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    ports:
      - "${NODE_EXPORTER_PORT:-9100}:9100"
    networks:
      - monitoring_network
    restart: unless-stopped
    profiles:
      - base-metrics
      - grafana-local
      - grafana-external
      - zabbix-local
      - zabbix-external
      - grafana-zabbix-external
      - full-stack
    logging: *default-logging

  zabbix-agent:
    image: zabbix/zabbix-agent2:${ZABBIX_VERSION:-latest}
    container_name: kopia-zabbix-agent
    environment:
      - ZBX_SERVER_HOST=${ZABBIX_SERVER_HOST:-zabbix-server}
      - ZBX_HOSTNAME=${KOPIA_CLIENT_HOSTNAME:-$(hostname)}
    volumes:
      - ${ZABBIX_EXTERNAL_SCRIPTS:-/usr/lib/zabbix/externalscripts}:/usr/lib/zabbix/externalscripts:ro
      - ${ZABBIX_AGENT_CONFIG:-/etc/zabbix/zabbix_agentd.d}:/etc/zabbix/zabbix_agentd.d:ro
    ports:
      - "10050:10050"
    networks:
      - monitoring_network
    restart: unless-stopped
    profiles:
      - zabbix-local
      - zabbix-external
      - grafana-zabbix-external
      - full-stack

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    container_name: kopia-grafana
    volumes:
      - ${GRAFANA_DATA_DIR:-/var/lib/grafana}:/var/lib/grafana
      - ${GRAFANA_CONFIG_DIR:-./grafana/provisioning}:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=${GRAFANA_PLUGINS:-alexanderzobnin-zabbix-app}
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    networks:
      - monitoring_network
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"
    profiles:
      - grafana-local
      - full-stack
    logging: *default-logging

networks:
  monitoring_network:
    name: ${MONITORING_NETWORK_NAME:-monitoring_network}
    driver: bridge
  kopia_network:
    external: true
    name: ${KOPIA_NETWORK_NAME:-kopia_network}