version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "${LOG_MAX_SIZE:-100M}"
    max-file: "${LOG_MAX_FILES:-7}"

services:
  kopia-server:
    image: ghcr.io/thespad/kopia-server:latest
    hostname: kopia-server
    container_name: kopia-server
    cap_add:
      - SYS_ADMIN
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - KOPIA_HTTPS=${KOPIA_TLS_ENABLED:-false}
      - KOPIA_UI_USERNAME=${KOPIA_SERVER_USERNAME:-admin}
      - KOPIA_UI_PASSWORD=${KOPIA_SERVER_PASSWORD:-admin}
      - KOPIA_PASSWORD=${KOPIA_REPO_PASSWORD:-change-me-please}
      - KOPIA_REPOSITORY_PATH=/repository
    volumes:
      - ${KOPIA_BASE_DIR:-/var/lib/kopia}:/config
      - ${KOPIA_CACHE_DIR:-/var/cache/kopia}:/cache
      - ${KOPIA_LOG_DIR:-/var/log/kopia}:/logs
      - /tmp:/tmp:shared
      - ${NAS_MOUNT_PATH:-/mnt/nas}:/repository
    devices:
      - /dev/fuse:/dev/fuse:rwm
    ports:
      - "${KOPIA_SERVER_PORT:-51515}:51515"
    networks:
      - kopia_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:51515/api/v1/repo/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging: *default-logging
    labels:
      - "com.kopia.version=${KOPIA_VERSION:-latest}"
      - "com.kopia.type=server"

networks:
  kopia_network:
    name: ${KOPIA_NETWORK_NAME:-kopia_network}
    driver: bridge