version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "${LOG_MAX_SIZE:-100M}"
    max-file: "${LOG_MAX_FILES:-7}"

services:
  kopia-server:
    image: kopia/kopia:latest
    hostname: kopia-server
    container_name: kopia-server
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - KOPIA_HTTPS=${KOPIA_TLS_ENABLED:-false}
      - KOPIA_PASSWORD=${KOPIA_REPO_PASSWORD:-change-me-please}
    volumes:
      - ${KOPIA_BASE_DIR:-/var/lib/kopia}:/app/config
      - ${KOPIA_CACHE_DIR:-/var/cache/kopia}:/app/cache
      - ${KOPIA_LOG_DIR:-/var/log/kopia}:/app/logs
      - /tmp:/tmp:shared
      - ${NAS_MOUNT_PATH:-/mnt/nas}:/repository
    ports:
      - "${KOPIA_SERVER_PORT:-51515}:51515"
    networks:
      - kopia_network
    restart: unless-stopped
    command: [
      "server", "start",
      "--address=0.0.0.0:51515",
      "--server-username=${KOPIA_SERVER_USERNAME:-admin}",
      "--server-password=${KOPIA_SERVER_PASSWORD:-admin}",
      "--insecure",
      "--without-password"
    ]
    healthcheck:
      test: ["CMD", "pgrep", "kopia"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  kopia_network:
    name: ${KOPIA_NETWORK_NAME:-kopia_network}
    driver: bridge