version: '3.8'

services:
  kopia-server:
    image: kopia/kopia:latest
    container_name: kopia-server
    volumes:
      - ${KOPIA_BASE_DIR}:${KOPIA_BASE_DIR}:rw
      - ${NAS_MOUNT_PATH}:${NAS_MOUNT_PATH}:rw
      - /var/log/kopia:/var/log/kopia:rw
      - ${KOPIA_CACHE_DIR:-/var/cache/kopia}:/app/cache:rw
    environment:
      - KOPIA_PASSWORD=${KOPIA_REPO_PASSWORD}
      - TZ=${TZ:-UTC}
    command: >
      server start
      --address 0.0.0.0:${KOPIA_SERVER_PORT}
      --server-username ${KOPIA_SERVER_USERNAME}
      --server-password ${KOPIA_SERVER_PASSWORD}
      ${KOPIA_SECURE_MODE:+--tls-generate-cert}
      ${KOPIA_SECURE_MODE:-"--insecure"}
      ${KOPIA_SERVER_ALLOWED_IPS:+--server-control-access=${KOPIA_SERVER_ALLOWED_IPS}}
      --server-cache-directory=/app/cache
      --max-upload-speed=${KOPIA_UPLOAD_LIMIT:-0}
      --max-download-speed=${KOPIA_DOWNLOAD_LIMIT:-0}
    ports:
      - "${KOPIA_SERVER_PORT}:${KOPIA_SERVER_PORT}"
    networks:
      - kopia_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '${KOPIA_SERVER_CPU_LIMIT:-2}'
          memory: ${KOPIA_SERVER_MEM_LIMIT:-2G}
    healthcheck:
      test: ["CMD", "kopia", "repository", "status"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-100M}"
        max-file: "${LOG_MAX_FILES:-7}"

networks:
  kopia_network:
    driver: bridge