version: '3.8'

services:
  kopia-backup:
    image: kopia/kopia:latest
    container_name: kopia-client
    volumes:
      - ${KOPIA_CONFIG_DIR}:/app/config
      - ${KOPIA_CACHE_DIR}:/app/cache
      - /var/log/kopia:/var/log/kopia
    environment:
      - KOPIA_PASSWORD=${KOPIA_REPO_PASSWORD}
      - TZ=UTC
    command: >
      snapshot create
      /backup
      --override-hostname=example-hostname
      --compression=zstd-fastest
      --parallel=${KOPIA_PARALLEL_CLIENT:-4}
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: ${KOPIA_CLIENT_CPU_LIMIT:-4}
          memory: ${KOPIA_CLIENT_MEM_LIMIT:-4G} 