global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "rules/kopia_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093  # Uncomment if you want to use Alertmanager

scrape_configs:
  - job_name: 'kopia'
    basic_auth:
      username: ${PROMETHEUS_AUTH_USER}
      password: ${PROMETHEUS_AUTH_PASSWORD}
    static_configs:
      - targets: ['kopia-exporter:9091']
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: '${KOPIA_CLIENT_HOSTNAME}'
    metric_relabel_configs:
      - source_labels: [source]
        target_label: backup_source
        regex: '(.+)'
        replacement: '$1'

  - job_name: 'node'
    basic_auth:
      username: ${PROMETHEUS_AUTH_USER}
      password: ${PROMETHEUS_AUTH_PASSWORD}
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: '${KOPIA_CLIENT_HOSTNAME}'

  - job_name: 'kopia-server'
    metrics_path: '/metrics'
    scheme: '${KOPIA_SECURE_MODE:+https}${KOPIA_SECURE_MODE:-http}'
    static_configs:
      - targets: ['${KOPIA_SERVER_IP}:${KOPIA_SERVER_PORT}']
    tls_config:
      insecure_skip_verify: ${KOPIA_TLS_SKIP_VERIFY:-false} 